version: 2
updates:
    # configuration for the root directory
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
            interval: "weekly"
    - package-ecosystem: "docker"
      directory: "/"
      schedule:
            interval: "weekly"
    # configuration for the database directory
    - package-ecosystem: "pip"
      directory: "/database"
      schedule:
            interval: "daily"
    - package-ecosystem: "docker"
      directory: "/database"
      schedule:
            interval: "weekly"
    - package-ecosystem: "docker"
      directory: "/database/.devcontainer"
      schedule:
            interval: "weekly"
    # configuration for the server directory
    - package-ecosystem: "pip"
      directory: "/server"
      schedule:
            interval: "daily"
    - package-ecosystem: "docker"
      directory: "/server"
      schedule:
            interval: "weekly"
    - package-ecosystem: "docker"
      directory: "/server/.devcontainer"
      schedule:
            interval: "weekly"