version: '3.8'

services: 
  fm_database:
    image: nstoik/fm_database:latest
    container_name: fm_database
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - farm_monitor
    depends_on:
      - "fm_db"
    restart: unless-stopped
  fm_db:
    image: postgres:11
    container_name: "fm_db"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: farm_monitor
      POSTGRES_USER: fm
      POSTGRES_DB: farm_monitor.db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    networks:
      - farm_monitor
  fm_pgadmin:
    container_name: fm_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: fm@farmmonitor.ca
      PGADMIN_DEFAULT_PASSWORD: farm_monitor
    volumes:
        - pgadmin:/root/.pgadmin
        - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - farm_monitor
    restart: unless-stopped
  
volumes:
  dbdata:
  pgadmin:

networks:
  farm_monitor:
    name: farm_monitor
    external: true