version: "3.8"

# docker-compose.dev.yml provides some overrides over the
# docker-compose.prod.yml file.

services:
    server:
        image: nstoik/farm_monitor_server:dev

    # in order to reduce the number of unique containers, we use the same container
    # as fm_server since the fm_database package and commands are included in
    # that container.
    database_management:
        image: nstoik/farm_monitor_server:dev

    api:
        image: nstoik/farm_monitor_api:dev

    frontend:
        image: nstoik/farm_monitor_frontend:dev

    # traefik contrainer configuration below
    traefik:
        ports:
            - 80:80
            # The Web UI (enabled by --api.insecure=true)
            - "8080:8080"
        volumes:
            - ./traefik/traefik.dev.yml:/etc/traefik/traefik.yml
