version: '3.8'

services: 
  fm_database:
    image: nstoik/fm_database:latest
    container_name: fm_database
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - farm_monitor
    depends_on:
      - "db"
  db:
    image: postgres:11
    container_name: "db"
    restart: always
    environment:
      POSTGRES_PASSWORD: farm_monitor
      POSTGRES_USER: fm
      POSTGRES_DB: farm_monitor.db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    networks:
      - farm_monitor
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
        - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - farm_monitor
    restart: unless-stopped
  
volumes:
  dbdata:
  pgadmin:

networks:
  farm_monitor:
    name: farm_monitor
    external: true