version: '3.8'

services: 
  fm_database:
    image: nstoik/fm_database:latest
    container_name: fm_database
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - farm_monitor
    depends_on:
      - "db"
  db:
    image: postgres:11
    container_name: "db"
    restart: always
    environment:
      POSTGRES_PASSWORD: farm_monitor
      POSTGRES_USER: fm
      POSTGRES_DB: farm_monitor.db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    networks:
      - farm_monitor
  
volumes:
  dbdata:

networks:
  farm_monitor:
    name: farm_monitor
    external: true