version: '3.8'

services: 
  fm_server:
    image: nstoik/fm_server:latest
    container_name: fm_server
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 5554:5554/tcp
    networks:
      - farm_monitor
    depends_on:
      - "db"
  db:
    image: postgres:11
    container_name: "db"
    restart: always
    environment:
      POSTGRES_PASSWORD: farm_monitor
      POSTGRES_USER: fm
      POSTGRES_DB: farm_monitor.db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "logs:/logs"
    networks:
      - farm_monitor
  
volumes:
  dbdata:
  logs:

networks:
  farm_monitor:
    name: farm_monitor