version: "3.8"

# docker-compose.dev.yml provides some overrides over the
# docker-compose.prod.yml file.

services:
    server:
        image: nstoik/farm_monitor_server:dev

    server_worker:
        image: nstoik/farm_monitor_server:dev

    # in order to reduce the number of unique containers, we use the same container
    # as fm_server since the fm_database package and commands are included in
    # that container.
    database_management:
        image: nstoik/farm_monitor_server:dev

    api:
        image: nstoik/farm_monitor_api:dev
        # command: ["pipenv", "run", "gunicorn", "fm_api.wsgi:app", "--bind", "0.0.0.0:8000", "--access-logfile", "-"]

    frontend:
        image: nstoik/farm_monitor_frontend:dev

    # traefik contrainer configuration below
    traefik:
        ports:
            - 80:80
            # The Web UI (enabled by --api.insecure=true)
            - "8080:8080"
            # for RabbitMQ
            - "5672:5672"
            # For the presence notifer
            #- "5554:5554/udp"
        volumes:
            - ./traefik/traefik.dev.yml:/etc/traefik/traefik.yml
