version: '3.8'

services: 
  fm_server:
    image: nstoik/fm_server:latest
    container_name: fm_server
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 5554:5554/tcp
    networks:
      - farm_monitor
    volumes:
      - "logs:/logs"
  
volumes:
  logs:

networks:
  farm_monitor:
    name: farm_monitor