version: "3.8"

services:
    server:
        image: nstoik/farm_monitor_server:latest
        container_name: fm_server
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - ${FM_SERVER_PRESENCE_PORT}:5554/udp # presence service port
        networks:
            - farm_monitor
        volumes:
            - "logs:/logs"
        depends_on:
            - "database"
        restart: on-failure

    # in order to reduce the number of unique containers, we use the same container
    # as fm_server since the fm_database package and commands are included in
    # that container.
    database_management:
        image: nstoik/farm_monitor_server:latest
        container_name: fm_database_management
        command: ["pipenv", "run", "fm_database", "update", "database-upgrade", "--revision", "head"]
        build:
            context: ./server
            dockerfile: Dockerfile
        networks:
            - farm_monitor
        depends_on:
            - "database"
        restart: on-failure

    api:
        image: nstoik/farm_monitor_api:latest
        container_name: fm_api
        build:
            context: ./api
            dockerfile: Dockerfile
        ports:
            - ${FM_API_PORT}
        networks:
            - farm_monitor
        restart: unless-stopped
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.flask.rule=Host(`flask.localhost`)"

    frontend:
        image: nstoik/farm_monitor_frontend:latest
        container_name: fm_frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
            # args:
        depends_on:
            - api
        restart: unless-stopped

    # traefik contrainer configuration below
    traefik:
        image: traefik:latest
        container_name: fm_traefik
        networks:
            - farm_monitor
        # ports are set in the docker-compose.dev and docker-compose.prod files
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        restart: unless-stopped
        depends_on:
            - frontend
            - api
            - database_management
            - server
    
    
    # standard docker containers below

    rabbitmq:
        image: rabbitmq:management
        container_name: fm_rabbitmq
        hostname: rabbitmq
        volumes:
            #- ./.docker/rabbitmq/etc/:/etc/rabbitmq/
            - rabbitmq_data:/var/lib/rabbitmq/
            #- ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
        environment:
            RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
            RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
            RABBITMQ_DEFAULT_VHOST: "${RABBITMQ_DEFAULT_VHOST}"
        ports:
            - ${RABBITMQ_DEFAULT_PORT}:5672 # RabbitMQ port
            - ${RABBITMQ_MANAGEMENT_PORT}:15672 # Management interface
        networks:
            - farm_monitor
        restart: unless-stopped

    flower:
        image: mher/flower:latest
        container_name: fm_flower
        volumes:
            - "flower_data:/data"
        environment:
            - CELERY_BROKER_URL=${FLOWER_CELLERY_BROKER_URL}
        ports:
            - ${FLOWER_PORT}:5555 # flower web interface
        networks:
            - farm_monitor
        restart: unless-stopped

    database:
        image: postgres:11
        container_name: fm_database
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - "dbdata:/var/lib/postgresql/data"
        networks:
            - farm_monitor

    pgadmin:
        container_name: fm_pgadmin
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        volumes:
            - pgadmin:/root/.pgadmin
            - pgadmin:/var/lib/pgadmin
        ports:
            - ${PGADMIN_PORT}:80
        networks:
            - farm_monitor
        restart: unless-stopped

volumes:
    logs:
    rabbitmq_data:
    flower_data:
    dbdata:
    pgadmin:

networks:
    farm_monitor:
        name: farm_monitor
