version: "3.8"

# docker-compose.dev.yml provides some overrides over the
# docker-compose.prod.yml file.

services:
    server:
        image: nstoik/fm_server:dev
        build:
            target: dev-stage

    server_worker:
        image: nstoik/fm_server:dev
        build:
            target: dev-stage

    # in order to reduce the number of unique containers, we use the same container
    # as fm_server since the fm_database package and commands are included in
    # that container.
    database_management:
        image: nstoik/fm_server:dev
        build:
            target: dev-stage

    api:
        image: nstoik/fm_api:dev
        # command: ["pipenv", "run", "gunicorn", "fm_api.wsgi:app", "--bind", "0.0.0.0:8000", "--access-logfile", "-"]
        labels:
          - "traefik.http.routers.fm_api.rule=PathPrefix(`/api`)"
          - "traefik.http.routers.fm_api.entrypoints=web"

    frontend:
        image: nstoik/fm_frontend:dev
        labels:
          - "traefik.http.routers.fm_frontend.rule=PathPrefix(`/frontend`)"
          - "traefik.http.routers.fm_frontend.entrypoints=web"


    # traefik contrainer configuration below
    traefik:
        ports:
            - 80:80
            # - 443:443
            # The Web UI (enabled by --api.insecure=true)
            - "8080:8080"
            # for RabbitMQ
            - "5672:5672"
            # For the presence notifer
            #- "5554:5554/udp"
        volumes:
            - ./traefik/traefik.dev.yml:/etc/traefik/traefik.yml

    # standard docker containers below

    rabbitmq:
        labels:
        # RabbitMQ Management interface
          - "traefik.http.routers.fm_rabbitmq.rule=PathPrefix(`/rabbitmq`)"
          - "traefik.http.routers.fm_rabbitmq.entrypoints=web"
        # RabbitMQ
          - "traefik.tcp.routers.fm_rabbitmq-connect.rule=HostSNI(`*`)"

    flower:
        labels:
          - "traefik.http.routers.flower.rule=PathPrefix(`/flower`)"
          - "traefik.http.routers.fm_flower.entrypoints=web"

    pgadmin:
        labels:
            - "traefik.http.routers.fm_pgadmin.rule=PathPrefix(`/pgadmin`)"
            - "traefik.http.routers.fm_pgadmin.entrypoints=web"
