entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'
  rabbitmq:
    address: ':5672'
  # presence:
  #  address: ':5554/udp'

# for health checks
ping:
  entryPoint: web


# Traefik dashboard over http
api:
  dashboard: true
  insecure: false

log:
  level: INFO

accessLog: {}

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false # containers are not discovered automatically
    network: farm_monitor
    # only create routes for containers that have this label.
    constraints: "Label(`custom.label`,`farm_monitor`)"

certificatesResolvers:
  letsencrypt:
    # Enable ACME (Let's Encrypt): automatic SSL.
    acme:

      # Email address used for registration.
      email: "nelsonstoik@gmail.com"

      # File or key used for certificates storage.
      storage: "/letsencrypt/acme.json"

      # CA server to use.
      # Uncomment the line to use Let's Encrypt's staging server,
      # leave commented to go to prod.
      #
      # Optional
      # Default: "https://acme-v02.api.letsencrypt.org/directory"
      #
      #caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"

      # Use a DNS-01 ACME challenge rather than HTTP-01 challenge.
      # Note: mandatory for wildcard certificate generation.
      #
      # Optional
      #
      dnsChallenge:

        # DNS provider used.
        #
        # Required
        #
        provider: cloudflare

        # Use following DNS servers to resolve the FQDN authority.
        #
        # Optional
        # Default: empty
        #
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"