# listen on port 80
[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.presence]
    address = ":5554/udp"

# Traefik dashboard over http
[api]
insecure = true

[log]
level = "INFO"

[accessLog]

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    # containers are not discovered automatically
    exposedByDefault = false
    network = "farm_monitor"