entryPoints:
  web:
    address: ':80'
  presence:
    address: ':5554/udp'

# Traefik dashboard over http
api:
  dashboard: true
  insecure: true

log:
  level: DEBUG

accessLog: {}

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false # containers are not discovered automatically
    network: farm_monitor
