"""sqlalchemy 2 upgrade

Revision ID: 2d2cb1d0819e
Revises: 4bad90f63d47
Create Date: 2024-02-05 04:02:27.273118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d2cb1d0819e'
down_revision = '4bad90f63d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'device_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('device', 'hardware_version',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('device', 'software_version',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('device', 'creation_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('device', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('device', 'location',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('device', 'description',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('device', 'connected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('device', 'user_configured',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('device', 'grainbin_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('grainbin', sa.Column('device_id_str', sa.String(length=20), nullable=False))
    op.alter_column('grainbin', 'creation_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('grainbin', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('grainbin', 'location',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('grainbin', 'description',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('grainbin', 'user_configured',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint('grainbin_device_id_fkey', 'grainbin', type_='foreignkey')
    op.create_foreign_key(None, 'grainbin', 'device', ['device_id_str'], ['device_id'])
    op.drop_column('grainbin', 'device_id')
    op.alter_column('message', 'source',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('message', 'destination',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('message', 'classification',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('message', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('system_interface', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('system_interface', 'is_for_fm',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('system_interface', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('system_setup', 'first_setup_complete',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('system_setup', 'update_in_progress',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('system_setup', 'new_update_installed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('system_wifi', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('system_wifi', 'password',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('system_wifi', 'mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('user_roles', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_roles', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('system_wifi', 'mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('system_wifi', 'password',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('system_wifi', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('system_setup', 'new_update_installed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('system_setup', 'update_in_progress',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('system_setup', 'first_setup_complete',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('system_interface', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('system_interface', 'is_for_fm',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('system_interface', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('message', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('message', 'classification',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('message', 'destination',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('message', 'source',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.add_column('grainbin', sa.Column('device_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'grainbin', type_='foreignkey')
    op.create_foreign_key('grainbin_device_id_fkey', 'grainbin', 'device', ['device_id'], ['device_id'])
    op.alter_column('grainbin', 'user_configured',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('grainbin', 'description',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('grainbin', 'location',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('grainbin', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('grainbin', 'creation_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('grainbin', 'device_id_str')
    op.alter_column('device', 'grainbin_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('device', 'user_configured',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('device', 'connected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('device', 'description',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('device', 'location',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('device', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('device', 'creation_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('device', 'software_version',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('device', 'hardware_version',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('device', 'device_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
