"""add update_index to grainbin and device

Revision ID: 4bad90f63d47
Revises: e9b3d0614f90
Create Date: 2021-10-31 20:40:54.793419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bad90f63d47'
down_revision = 'e9b3d0614f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('total_updates', sa.Integer(), nullable=True))
    op.execute('UPDATE device SET total_updates = 0')
    op.alter_column('device', 'total_updates', existing_type=sa.INTEGER(), nullable=False)

    op.add_column('device_update', sa.Column('update_index', sa.Integer(), nullable=True))
    op.execute('UPDATE device_update SET update_index = 0')
    op.alter_column('device_update', 'update_index', existing_type=sa.INTEGER(), nullable=False)

    op.create_index(op.f('ix_device_update_update_index'), 'device_update', ['update_index'], unique=False)
    op.alter_column('grainbin', 'total_updates',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('grainbin_update', sa.Column('update_index', sa.Integer(), nullable=True))
    op.execute('UPDATE grainbin_update SET update_index = 0')
    op.alter_column('grainbin_update', 'update_index', existing_type=sa.INTEGER(), nullable=False)

    op.create_index(op.f('ix_grainbin_update_update_index'), 'grainbin_update', ['update_index'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grainbin_update_update_index'), table_name='grainbin_update')
    op.drop_column('grainbin_update', 'update_index')
    op.alter_column('grainbin', 'total_updates',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_device_update_update_index'), table_name='device_update')
    op.drop_column('device_update', 'update_index')
    op.drop_column('device', 'total_updates')
    # ### end Alembic commands ###
