"""add DeviceUpdate

Revision ID: d09ea0b9c0c0
Revises: 1a110acdc798
Create Date: 2021-10-21 01:30:38.861166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd09ea0b9c0c0'
down_revision = '1a110acdc798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('interior_temp', sa.Float(), nullable=True),
    sa.Column('exterior_temp', sa.Float(), nullable=True),
    sa.Column('device_temp', sa.Float(), nullable=True),
    sa.Column('uptime', sa.Interval(), nullable=True),
    sa.Column('load_avg', sa.Integer(), nullable=True),
    sa.Column('disk_total', sa.Integer(), nullable=True),
    sa.Column('disk_used', sa.Integer(), nullable=True),
    sa.Column('disk_free', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_update_timestamp'), 'device_update', ['timestamp'], unique=True)
    op.drop_column('device', 'interior_temp')
    op.drop_column('device', 'load_avg')
    op.drop_column('device', 'device_temp')
    op.drop_column('device', 'exterior_temp')
    op.drop_column('device', 'disk_used')
    op.drop_column('device', 'current_time')
    op.drop_column('device', 'disk_total')
    op.drop_column('device', 'disk_free')
    op.drop_column('device', 'uptime')
    op.add_column('grainbin', sa.Column('bus_number_string', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grainbin', 'bus_number_string')
    op.add_column('device', sa.Column('uptime', postgresql.INTERVAL(), autoincrement=False, nullable=True))
    op.add_column('device', sa.Column('disk_free', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('device', sa.Column('disk_total', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('device', sa.Column('current_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('device', sa.Column('disk_used', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('device', sa.Column('exterior_temp', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
    op.add_column('device', sa.Column('device_temp', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
    op.add_column('device', sa.Column('load_avg', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('device', sa.Column('interior_temp', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_device_update_timestamp'), table_name='device_update')
    op.drop_table('device_update')
    # ### end Alembic commands ###
