name: API Build Status

on:
    push:
        paths:
            - 'api/**'

jobs:
    api-build:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: api/
      steps:
          - uses: actions/checkout@v4
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
                  python-version: '3.12'
          - name: Install Python dependencies
            run: |
              pip install pipenv
              pipenv install --dev
          - run: cp .env.example .env
          - name: Run Python lints
            run: pipenv run fm_api lint --check
          - name: Run Python tests
            run: pipenv run fm_api test --coverage
