name: Database Build Status

on:
    push:
        paths:
            - 'database/**'

jobs:
    database-build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                folders: [database, server, api]
            fail-fast: false
        defaults:
          run:
            working-directory: ${{ matrix.folders }}/
        steps:
          - name: Checkout
            uses: actions/checkout@v2.4.0
            with:
                  path: ${{ matrix.folders }}
          - name: Set up Python
            uses: actions/setup-python@v3
            with:
                  python-version: '3.10'
          - name: Install Python dependencies
            run: |
              pip install pipenv
              cd ${{ matrix.folders }}
              pipenv install --dev
          - run: cp ${{ matrix.folders }}/.env.example ${{ matrix.folders }}/.env
          - name: Run Python lints
            run: |
              cd ${{ matrix.folders }}
              pipenv run fm_${{ matrix.folders }} lint --check
          - name: Run Python tests
            run: |
              cd ${{ matrix.folders }}
              pipenv run fm_${{ matrix.folders }} test --coverage
