name: Database Build Status

on:
    push:
        paths:
            - '/database/**'

jobs:
    database-build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                folders: [database, server]
            fail-fast: true
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.4
              with:
                    path: ${{ matrix.folders }}
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                    python-version: 3.9
            - name: Install Python dependencies
              run: |
                pip install pipenv
                pipenv install --dev
            - run: cp .env.example .env
            - name: Run Python lints
              run: pipenv run fm_${{ matrix.folders }} lint --check
            - name: Run Python tests
              run: pipenv run fm_${{ matrix.folders }} test --coverage
