name: Frontend Build Status

on:
    push:
        paths:
            - 'frontend/**'

jobs:
    frontend-build:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: frontend/
      steps:
          - uses: actions/checkout@v4
          - name: Set up Node
            uses: actions/setup-node@v3
            with:
                  node-version: 16
          - name: Install NPM dependencies
            run: npm ci
          - name: Run NPM lints
            run: npm run lint
          - name: Run NPM tests
            run: npm run test:unit
