name: Frontend Build Status

on:
    push:
        paths:
            - 'frontend/**'

jobs:
    frontend-build:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: frontend/
      steps:
          - uses: actions/checkout@v4
          - name: Set up Node
            uses: actions/setup-node@v4
            with:
                  node-version: lts
          - name: Install NPM dependencies
            run: npm ci
          - name: Run NPM format
            run: npm run format:ci
          - name: Run NPM lint
            run: npm run lint
          - name: Run NPM type check
            run: npm run type-check
          - name: Run NPM tests
            run: npm run test:unit
          - name: Build
            run: npm run build
