name: Server Build Status

on:
    push:
        paths:
            - 'server/**'

jobs:
    server-build:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: server/
      steps:
          - uses: actions/checkout@v2.3.4
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
                  python-version: '3.10'
          - name: Install Python dependencies
            run: |
              pip install pipenv
              pipenv install --dev
          - run: cp .env.example .env
          - name: Run Python lints
            run: pipenv run fm_server lint --check
          - name: Run Python tests
            run: pipenv run fm_server test --coverage
